import type { Experiment } from '@/types/experiment'
import type { Note } from '@/types/note'
import type { Project } from '@/types/project'
import type { Prompt } from '@/types/prompt'
import type { Tool } from '@/types/tool'
import { nowISO } from './utils'

const ts = nowISO()

export const MOCK_TOOLS: Tool[] = [
  {
    id: 'tool-claude',
    name: 'Claude Code',
    type: 'terminal',
    category: 'code-agent',
    description: 'Agente de código via terminal',
    command: 'C:/Users/gcaio/AppData/Roaming/npm/node_modules/@anthropic-ai/claude-code/bin/claude.exe',
    icon: '🤖',
    isFavorite: true,
    openMode: 'internal',
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'tool-codex',
    name: 'Codex',
    type: 'terminal',
    category: 'code-agent',
    description: 'Agente de código OpenAI via CLI',
    command: 'C:/Users/gcaio/AppData/Roaming/npm/node_modules/@openai/codex/node_modules/@openai/codex-win32-x64/vendor/x86_64-pc-windows-msvc/bin/codex.exe',
    icon: '⚡',
    isFavorite: true,
    openMode: 'internal',
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'tool-grok',
    name: 'Grok',
    type: 'terminal',
    category: 'ai-chat',
    description: 'Grok CLI da xAI — terminal interativo',
    command: 'C:/Users/gcaio/.grok/bin/grok.exe',
    url: 'https://grok.com',
    icon: '🧠',
    isFavorite: true,
    openMode: 'internal',
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'tool-hermes',
    name: 'Hermes',
    type: 'web',
    category: 'agent',
    description: 'Hermes Agent — dashboard web com chat, kanban e memória',
    command: 'C:/Users/lecto/AppData/Local/hermes/hermes-agent/venv/Scripts/hermes.exe',
    url: 'http://localhost:9119',
    icon: '📡',
    isFavorite: true,
    openMode: 'internal',
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'tool-open-design',
    name: 'Open Design',
    type: 'web',
    category: 'design',
    description: 'Workspace agentic de design — protótipos, decks e UI com Hermes',
    url: 'http://localhost:7456',
    icon: '🎨',
    isFavorite: true,
    openMode: 'internal',
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'tool-notebooklm',
    name: 'NotebookLM',
    type: 'web',
    category: 'research',
    description: 'Pesquisa e síntese de documentos',
    url: 'https://notebooklm.google.com',
    icon: '📓',
    isFavorite: false,
    openMode: 'internal',
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'tool-obsidian',
    name: 'Obsidian',
    type: 'folder',
    category: 'notes',
    description: 'Vault pessoal de notas',
    path: 'C:/Users/lecto/OneDrive/Documentos/Lector BRAIN',
    icon: '💎',
    isFavorite: true,
    openMode: 'external',
    createdAt: ts,
    updatedAt: ts,
  },
]

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-vendas',
    name: 'Agente de vendas ao vivo',
    description: 'Sistema com LiveKit + Hermes para ajudar vendedor em tempo real.',
    status: 'testing',
    localPath: 'C:/Users/Caio/Projects/agente-vendas',
    links: [
      { id: 'link-livekit', label: 'LiveKit docs', url: 'https://docs.livekit.io' },
      { id: 'link-github', label: 'GitHub', url: 'https://github.com' },
    ],
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'proj-secretaria',
    name: 'SaaS secretária',
    description: 'Assistente virtual para agendamento e atendimento.',
    status: 'building',
    localPath: 'C:/Users/Caio/Projects/saas-secretaria',
    links: [{ id: 'link-stripe', label: 'Stripe', url: 'https://stripe.com/docs' }],
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'proj-proctoring',
    name: 'Proctoring IA',
    description: 'Monitoramento de provas com visão computacional.',
    status: 'idea',
    localPath: 'C:/Users/Caio/Projects/proctoring-ia',
    links: [],
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'proj-lp-det',
    name: 'LP DET',
    description: 'Landing page para produto DET.',
    status: 'building',
    localPath: 'C:/Users/Caio/Projects/lp-det',
    links: [{ id: 'link-figma', label: 'Figma', url: 'https://figma.com' }],
    createdAt: ts,
    updatedAt: ts,
  },
]

export const MOCK_PROJECT_TOOLS: Record<string, string[]> = {
  'proj-vendas': ['tool-hermes', 'tool-claude', 'tool-obsidian'],
  'proj-secretaria': ['tool-claude', 'tool-codex', 'tool-grok'],
  'proj-proctoring': ['tool-claude', 'tool-codex'],
  'proj-lp-det': ['tool-grok', 'tool-claude'],
}

export const MOCK_PROMPTS: Prompt[] = [
  {
    id: 'prompt-objecoes',
    title: 'Quebrar objeções',
    category: 'Agentes',
    content: 'Analise a objeção do cliente e sugira 3 respostas empáticas e persuasivas...',
    recommendedToolId: 'tool-hermes',
    projectId: 'proj-vendas',
    tags: ['vendas', 'live'],
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'prompt-arquitetura',
    title: 'Revisar arquitetura',
    category: 'Arquitetura',
    content: 'Revise esta arquitetura e identifique pontos fracos, gargalos e melhorias...',
    recommendedToolId: 'tool-claude',
    tags: ['arquitetura', 'review'],
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'prompt-landing',
    title: 'Gerar copy de landing',
    category: 'Landing Page',
    content: 'Crie uma landing page com hero, benefícios, prova social e CTA para...',
    recommendedToolId: 'tool-grok',
    projectId: 'proj-lp-det',
    tags: ['marketing', 'copy'],
    createdAt: ts,
    updatedAt: ts,
  },
]

export const MOCK_EXPERIMENTS: Experiment[] = [
  {
    id: 'exp-hermes-livekit',
    title: 'Hermes + LiveKit',
    objective: 'Capturar áudio de chamada e mandar para Hermes sugerir respostas.',
    result: 'Funcionou parcialmente. Latência aceitável, transcrição precisa de ajuste.',
    rating: 6,
    shouldContinue: true,
    projectId: 'proj-vendas',
    toolsUsed: ['tool-hermes', 'tool-claude'],
    commandsUsed: 'npm run dev\nhermes listen --port 8080',
    logs: 'Áudio capturado OK. Whisper local com delay de 2s.',
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'exp-codex-cli',
    title: 'Teste Codex CLI',
    objective: 'Validar fluxo de refatoração automática em projeto real.',
    result: 'Bom para tarefas pequenas. Projetos grandes precisam de contexto manual.',
    rating: 7,
    shouldContinue: true,
    projectId: 'proj-secretaria',
    toolsUsed: ['tool-codex'],
    commandsUsed: 'codex refactor src/api.ts',
    createdAt: ts,
    updatedAt: ts,
  },
]

export const MOCK_NOTES: Note[] = [
  {
    id: 'note-vendas-arch',
    title: 'arquitetura.md',
    content: '# Arquitetura — Agente de Vendas\n\n## Stack\n- LiveKit\n- Hermes\n- Whisper\n\n## Fluxo\n1. Captura áudio\n2. Transcrição\n3. Sugestão em tempo real',
    scope: 'project',
    projectId: 'proj-vendas',
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: 'note-claude',
    title: 'claude-code.md',
    content: '# Claude Code\n\nComandos úteis:\n- `claude` — iniciar sessão\n- `/help` — ajuda',
    scope: 'tool',
    toolId: 'tool-claude',
    createdAt: ts,
    updatedAt: ts,
  },
]